In [1]:
import numpy as np
import sys

## The Basics

In [2]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [3]:
b=np.array([[9.0,8.0,7.0],[6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
## get dimension

a.ndim

1

In [5]:
b.ndim

2

In [6]:
## get shape

b.shape

(2, 3)

In [7]:
a.shape

(3,)

In [8]:
## get data type

a.dtype

dtype('int16')

In [9]:
## get size (it's 2 bytes because we have written down int16 at the top)

a.itemsize

2

In [10]:
## get total size

a.nbytes

6

## Accessing/Changing specific elements, rows, columns etc.

In [11]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
a.shape

(2, 7)

In [13]:
## get a specific element [r,c]

a[1, 5]
#a[1, -2]

13

In [14]:
## get a specific row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
## get a specific column 

a[:, 4]

array([ 5, 12])

In [16]:
## getting a little more fancy [startindex:endindex:stepsize]

a[0, 1:-1:3]

array([2, 5])

In [17]:
## changing an item in the array

a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [19]:
a[:,2] = [3,10]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


## 3-D example

In [20]:
c = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
## getting specific element

c[0, 1, 0]

3

In [23]:
## replace

c[:,1,:] = [[9,9],[7,7]]
print(c)

[[[1 2]
  [9 9]]

 [[5 6]
  [7 7]]]


## Initializing Different Types of Arrays

In [24]:
## all 0s matrix

np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
## all 1s matrix

np.ones((2,6), dtype='int32')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [26]:
## any other number

np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [27]:
## any other number (full_like)

np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
## random decimal numbers

np.random.rand(4,2)

## to pass a shape variable as an input:

#np.random.random_sample(a.shape)

array([[0.69451673, 0.32192789],
       [0.82949127, 0.06477738],
       [0.76336305, 0.9071904 ],
       [0.52181091, 0.64173775]])

In [29]:
## random int values

np.random.randint(-18, 14, size=(4,2))

array([[-15, -16],
       [-12,  13],
       [ -3,   5],
       [-17, -14]])

In [30]:
## the identity matrix

np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [31]:
## repeat an array

arr = np.array([[1,2,4]])
r1 = np.repeat(arr,4, axis=0)
r1

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

In [32]:
m1 = np.ones((5,5), dtype = 'int16')
m1[1:4, 1:4] = np.zeros((3,3), dtype = 'int16') 
m1[2,2] = 9
m1

## alternative solution

#output = np.ones((5,5))
#print(output)

#z = np.zeros((3,3))
#z[1,1] = 9
#print(z)

#output[1:-1,1:-1] = z
#print(output)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

#### be careful when copying arrays

In [33]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [34]:
## to avoid that 

a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


## Mathematics

In [35]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [36]:
a + 2

array([3, 4, 5, 6])

In [37]:
a-2

array([-1,  0,  1,  2])

In [38]:
a * 2

array([2, 4, 6, 8])

In [39]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [40]:
b = np.array([1,0,1,1])
a+b

array([2, 2, 4, 5])

In [41]:
a **2

array([ 1,  4,  9, 16])

In [42]:
## trigonometry

np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [43]:
a = np.ones((2,3), dtype = 'int16')
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [44]:
## find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [46]:
stats = np.array([[1,2,3],[4,6,8]])
stats

array([[1, 2, 3],
       [4, 6, 8]])

In [51]:
stats.min()
stats.min(axis = 1) # gives the min of the first row and the min of the second row

array([1, 4])

In [49]:
stats.max()

8

In [50]:
stats.mean()

4.0

In [52]:
np.sum(stats)

24

In [53]:
np.sum(stats, axis=0) # summing downwards

array([ 5,  8, 11])

### Reorganizing Arrays

In [61]:
before = np.array([[1,2,3, 4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [64]:
## vertically stacking matrices/vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
## horizontally stacking matrices/vectors

np.hstack([v1,v2,v1,v1,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

### Miscellaneous

#### Load From Data File

In [79]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')

#### Boolean Masking and Advanced Indexing

In [80]:
filedata > 30

array([[False, False, False, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [81]:
filedata[filedata >=27]

array([196,  75,  34,  42,  33, 766,  75,  55,  33, 999,  78,  76,  88],
      dtype=int32)

In [84]:
## it's possible to index with a list

a = np.array([1,2,3,4,5,6,7,8,9,10,11])

a[[1,3,8,9]]

array([ 2,  4,  9, 10])

In [85]:
np.any(filedata >5, axis=0) ## goes through all the data frame col by col and generates a boolean output (at least one row satisfying the condition is ok)



array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True])

In [87]:
np.all(filedata >50, axis=0) ## goes through all the data frame col by col and generates a boolean output (all the rows must satisfy the condition)



array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [93]:
np.all(filedata > 30, axis=1)

array([False, False, False])

In [96]:
((filedata > 30) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [99]:
## to get the inverse of the results that we obtain above:

(~((filedata > 30) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True, False,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [118]:
quiz = np.array([[1,2,3,4,5], 
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20],
               [21,22,23,24,25],
               [26,27,28,29,30]])



In [119]:
## to obtain 11,12,16,17

##

quiz[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [120]:
## to obtain 2,8,14,20

quiz[[0,1,2,3],[1,2,3,4]]



array([ 2,  8, 14, 20])

In [121]:
## to obtain 4,5, 24,25,29 and 30

quiz[[0,4,5],[3,4]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [136]:
import numpy as np

arr = np.arange(1,36).reshape(7, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])